spec:
  inputs:
    registry:
      description: "Selectel container registry name"
      options:
        - bro-dev
        - bro-prod
      default: bro-dev

---
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

stages:
  - test
  - plan
  - cleanup

variables:
  PYTHON_IMAGE: registry.gftech.ru/devops/docker-images/cr-cleanup-python:latest
  DRY_RUN: "true"

.python_env:
  image:
    name: ${PYTHON_IMAGE}
    entrypoint: [ "" ]
  tags:
    - ops-docker

# ---------------- TESTS ----------------
run_code_tests:
  extends: .python_env
  stage: test
  variables:
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONPATH: "."
    PYLINT_OPTS: "--disable=all --enable=F,E,W --disable=W0718 --fail-under=9.0"
    PYLINT_FILES: "*.py"
    TEST_DIR: "tests"
    JUNITXML: "report.xml"
  script:
    - pylint ${PYLINT_OPTS} ${PYLINT_FILES}
    - python3 -m pytest --junitxml=${JUNITXML} --color=yes ${TEST_DIR}
  artifacts:
      when: always
      reports:
        junit: ${JUNITXML}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      changes: &change_files
          - "**/*.py"
          - "**/*.yaml"
          - "**/*.yml"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: *change_files

# ---------------- PLAN ----------------
cleanup_plan:
  extends: .python_env
  needs: 
      - job: "run_code_tests"
        optional: true
  stage: plan
  environment: $REGISTRY
  script:
    - python cleanup_registry.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  parallel:
    matrix:
      - REGISTRY:
        - bro-dev
        - bro-prod

cleanup_plan_$[[ inputs.registry ]]:
  extends: .python_env
  needs: 
      - job: "run_code_tests"
        optional: true
  stage: plan
  environment: $[[ inputs.registry ]]
  script:
    - python cleanup_registry.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

# ---------------- CLEANUP ----------------
cleanup_execute_$[[ inputs.registry ]]:
  extends: .python_env
  needs: 
    - job: "run_code_tests"
      optional: true
    - job: "registry_cleanup_plan"
      optional: true
  stage: cleanup
  environment: $[[ inputs.registry ]]
  variables:
    DRY_RUN: "false"
  script:
    - python cleanup_registry.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
